### ISSUE TITLE
can you list out requirement for tensorflow and keras?

### ISSUE THREAD

**Issue by charliewang789** [lacmus-foundation/lacmus#124]
what exactly version does it need?

i am hitting all sort of issues.

**Comment by prickly-u** [comment]
@charliewang789 According to dockerfile 
https://github.com/lacmus-foundation/lacmus/blob/master/Server.gpu.dockerfile
Tensorflow 2.1.1 and Keras 2.3.1 should work normally

**Comment by gosha20777** [comment]
https://github.com/lacmus-foundation/lacmus/issues/125

@charliewang789 yep
Tensorflow 2.1.1 or Tensorflow 1.14
Keras 2.3.1
