### ISSUE TITLE
add requirements.txt

### ISSUE THREAD

**Issue by gosha20777** [lacmus-foundation/lacmus#125]
add `requirements.txt` with dependencies

**Comment by aleksandr-kotlyar** [comment]
Resolved? I see requirements.txt is already in project https://github.com/lacmus-foundation/lacmus/blob/f1dd0da5fb1c04d12ad25e7f67b5dd2a98f595d4/requirements.txt

**Comment by gosha20777** [comment]
@aleksandr-kotlyar yep, I think I can close this issue
