### ISSUE TITLE
Bug: Could not find registration proxy for IID: {ADD8BA80-002B-8F0F-00C04FD062}

### ISSUE THREAD

**Issue by Denaizer** [lacmus-foundation/lacmus#67]
**Describe the bug**
Version - 0.3.2 
os - Win10 

при попытке загрузить директорию с файлами через USB выдает ошибку 
*Сообщение программы:*
```
Error Интерфейс не зарегистрирован
Не удалось найти регистрацию прокси-сервера для IID: {ADD8BA80-002B-8F0F-00C04FD062}
```

**Comment by Denaizer** [comment]
этот баг есть и на предыдущем релизе

**Comment by gosha20777** [comment]
The issue closed due to the transition of the repository to https://github.com/lacmus-foundation/lacmus-desctop-app/
